version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gps-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gpsdb
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: gps-rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port (http://localhost:15672)